//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _Parcial2_Ap2_Anthony_Santana_.Ui.Consultas
{


    public partial class CPresupuesto
    {
    }
}
